export const donation = [
  {
    type: 'donation',
    image: '/donation/wesh.png',
    description: 'NFT trader & collector. Web3 apprentice. @GCLX holder.',
    title: 'wesh.eth',
    twitter: 'https://twitter.com/mekawesh',
    donation: 5.16,
  },
  {
    type: 'donation',
    image: '/donation/gclx.png',
    description:
      'GCLX NFT project is a Performance Art. It made by 1000 randomly generated NFTs, sold for 0.01 ETH. Using funny content to tell Chinese NFT players what NFTs truely are.',
    title: 'GuoChanLiangXing',
    website: 'https://gclx.xyz/',
    opensea: 'https://opensea.io/collection/gclx',
    twitter: 'https://twitter.com/gclxnft',
    donation: 0.5,
  },
  {
    type: 'donation',
    image: '/donation/jolestar.jpeg',
    description: 'BlockChain Maximalism, Westar Labs/Starcoin ($stc)',
    title: 'jolestar',
    twitter: 'https://twitter.com/jolestar',
    donation: 0.1,
  },
  {
    type: 'donation',
    image: '/donation/west.jpeg',
    description:
      'Co-Founder of .bit, Web3 Builder, Design lovers, NFT Collector.',
    title: 'west.bit',
    website: 'https://app.did.id/explorer?inviter=west.bit',
    twitter: 'https://twitter.com/kylexiang',
    donation: 0.072,
  },
  {
    type: 'donation',
    image: '/donation/0xmetapapa.jpeg',
    description: '良心家人，《地漏》守护者，@0xmetapapa',
    title: '0xmetapapa',
    twitter: 'https://twitter.com/0xmetapapa',
    donation: 0.069,
  },
  {
    type: 'donation',
    image: '/donation/harry.png',
    description: 'professor / entrepreneur / maker',
    title: 'Harry',
    twitter: 'https://twitter.com/harryjwang',
    donation: 0.042,
  },
  {
    type: 'donation',
    image: '/donation/su.jpeg',
    description: '良心家人',
    title: 'su007.eth',
    twitter: 'https://twitter.com/wutaner',
    donation: 0.02,
  },
  {
    type: 'donation',
    image: '/donation/dinglun.png',
    title: 'dinglun',
    twitter: 'https://twitter.com/dinglunnft',
    donation: 0.02,
  },
  {
    type: 'donation',
    image: '/donation/0xflipping.jpg',
    title: '0xflipping',
    description: 'WAGMI',
    twitter: 'https://twitter.com/zxxkill',
    donation: 0.01,
  },
  {
    type: 'donation',
    image: '/donation/8757.png',
    title: '8757.eth',
    description: '加密兔',
    website: 'https://mirror.xyz/cryptorabit.eth',
    twitter: 'https://twitter.com/jiashu211',
    donation: 0.01,
  },
  {
    type: 'donation',
    image: '/donation/uniwarp.png',
    title: 'Uniwarp',
    description: 'The multiverse where no unicorn has gone before.',
    website: 'https://opensea.io/collection/uniwarp',
    twitter: 'https://twitter.com/uniwarp_',
    donation: 0.01,
  },
  {
    type: 'donation',
    image: '/donation/ch3coooh.png',
    title: 'ch3coooh',
    description: '一个在寻找 Web3 机会的大厂在职产品经理',
    twitter: 'https://twitter.com/ch3coooh/',
    donation: 0.002,
  },
  {
    type: 'donation',
    image: '/donation/lvsao.jpeg',
    title: 'lvsao',
    description: '专注被割',
    twitter: 'https://twitter.com/metalvsao/',
    donation: 0.002,
  },
  {
    type: 'donation',
    image: '/donation/code378.jpeg',
    title: 'code378',
    website: 'https://workshop.bilibili.com/live2d/15301',
    donation: 0.001,
  },
  {
    type: 'instruction',
  },
];
